(() => {
  const fragrances = [
    {id:'vesper',name:'Vesper Rose',family:'floral',label:'Soft floral',notes:'Rose · Pink pepper · White musk',opening:'Pink pepper, bergamot',heart:'Rose petals, peony',base:'White musk, pale woods',mood:'Soft, romantic, quietly expressive.',why:'An imagined floral composition with a peppery opening and a gentle musky finish.',tone:''},
    {id:'sol',name:'Sol Mist',family:'fresh',label:'Fresh & bright',notes:'Bergamot · Neroli · Green tea',opening:'Bergamot, mandarin',heart:'Neroli, green tea',base:'Soft cedar, clean musk',mood:'Luminous, airy, easygoing.',why:'An imagined citrus composition built around brightness, green notes, and a light woody finish.',tone:'tone-fresh'},
    {id:'santal',name:'Santal Dusk',family:'woody',label:'Warm woods',notes:'Cardamom · Iris · Sandalwood',opening:'Cardamom, black pepper',heart:'Iris, violet leaf',base:'Sandalwood, amber',mood:'Warm, textured, contemplative.',why:'An imagined woody composition with dry spice, powdery iris, and a warm base.',tone:'tone-woody'}
  ];
  let filter='all',query='',view='discover',selected=new Set(),saved=new Set(),timer,detailId;
  const $=s=>document.querySelector(s);
  const item=id=>fragrances.find(f=>f.id===id);
  const announce=text=>{clearTimeout(timer);$('#toast').textContent=text;$('#toast').classList.add('visible');timer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);};
  const card=f=>`<article class="product-card"><div class="product-photo"><img class="${f.tone}" src="assets/aurea-editorial.webp" alt="Editorial fragrance still life" loading="lazy"><span class="edition-label">ILLUSTRATIVE SCENT / ${f.label.toUpperCase()}</span><button type="button" class="save" data-save="${f.id}" aria-pressed="${saved.has(f.id)}" aria-label="${saved.has(f.id)?'Unsave':'Save'} ${f.name}">${saved.has(f.id)?'♥':'♡'}</button></div><div class="product-info"><p class="kicker">${f.label}</p><h3>${f.name}</h3><p>${f.notes}</p><div class="card-actions"><button type="button" data-detail="${f.id}">Discover the notes ↗</button><button type="button" data-compare="${f.id}" aria-pressed="${selected.has(f.id)}">${selected.has(f.id)?'✓ In comparison':'+ Compare'}</button></div></div></article>`;
  function render(){
    const matches=fragrances.filter(f=>(filter==='all'||filter===f.family)&&`${f.name} ${f.notes} ${f.label}`.toLowerCase().includes(query));
    $('#product-grid').innerHTML=matches.map(card).join('');$('#empty-search').hidden=matches.length>0;$('#result-count').textContent=`${matches.length} fragrance${matches.length===1?'':'s'}`;
    $('#save-count').textContent=saved.size;$('#compare-count').textContent=selected.size;
    $('#archive-grid').innerHTML=fragrances.filter(f=>saved.has(f.id)).map(card).join('');$('#empty-archive').hidden=saved.size>0;
    const chosen=[...selected].map(item);
    $('#comparison').innerHTML=chosen.length===2?`<div class="compare-pair">${chosen.map(f=>`<article class="compare-item"><div class="compare-top"><p class="kicker">${f.label}</p><h3>${f.name}</h3><button type="button" data-compare="${f.id}">Remove from comparison</button></div><dl><div><dt>Character</dt><dd>${f.mood}</dd></div><div><dt>Opening notes</dt><dd>${f.opening}</dd></div><div><dt>Heart notes</dt><dd>${f.heart}</dd></div><div><dt>Base notes</dt><dd>${f.base}</dd></div></dl><p>Illustrative profile. No longevity or performance claims.</p></article>`).join('')}</div>`:`<div class="empty"><span class="empty-mark" aria-hidden="true">↔</span><h3>${chosen.length?'One more perspective.':'A little perspective helps.'}</h3><p>${chosen.length?`${chosen[0].name} is selected. Choose one more fragrance to compare their notes.`:'Choose two fragrances from the collection to see their differences side by side.'}</p><button type="button" class="primary" data-go="discover">Choose fragrances ↗</button></div>`;
  }
  function go(next){view=next;document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});window.scrollTo({top:0,behavior:'instant'});const heading=document.querySelector(`#${next} h1`);heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}
  document.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b)return;
    if(b.dataset.view||b.dataset.go){go(b.dataset.view||b.dataset.go);return;}
    if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();return;}
    if(b.dataset.save){const id=b.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);const inDialog=b.closest('dialog');render();if(inDialog){b.textContent=saved.has(id)?'Saved to archive ✓':'Save to my archive';b.setAttribute('aria-pressed',String(saved.has(id)));}else{const replacement=document.querySelector(`#${view} [data-save="${id}"]`)||document.querySelector(`#${view} [data-save], #${view} [data-go]`);replacement?.focus({preventScroll:true});}announce(`${item(id).name} ${saved.has(id)?'saved to':'removed from'} your archive.`);return;}
    if(b.dataset.compare){const id=b.dataset.compare;if(selected.has(id))selected.delete(id);else if(selected.size<2)selected.add(id);else{announce('Compare two at a time. Remove one selection to add another.');return;}render();(document.querySelector(`#${view} [data-compare="${id}"]`)||document.querySelector(`#${view} [data-go]`))?.focus({preventScroll:true});announce(selected.size===2?'Two fragrances selected. Open Compare to explore their notes.':`${selected.size} fragrance selected for comparison.`);return;}
    if(b.dataset.detail){detailId=b.dataset.detail;const f=item(detailId);$('#detail-content').innerHTML=`<div class="detail-grid"><img src="assets/aurea-editorial.webp" alt="Amber fragrance bottle with a burgundy rose"><div class="detail-writing"><p class="kicker">${f.label} / Concept fragrance</p><h2 id="detail-title">${f.name}</h2><p>${f.why}</p><div class="note-timeline"><div><span>01 / THE OPENING</span>${f.opening}</div><div><span>02 / THE HEART</span>${f.heart}</div><div><span>03 / THE BASE</span>${f.base}</div></div><button class="primary" type="button" data-save="${f.id}" aria-pressed="${saved.has(f.id)}">${saved.has(f.id)?'Saved to archive ✓':'Save to my archive'}</button><p>Illustrative scent profile. Sampling would be needed to learn how a real fragrance wears.</p></div></div>`;$('#product-dialog').showModal();return;}
    if(b.classList.contains('close'))$('#product-dialog').close();
  });
  $('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render();});
  $('#clear-search').addEventListener('click',()=>{filter='all';query='';$('#search').value='';document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='all')));render();$('#search').focus();});
  $('#product-dialog').addEventListener('close',()=>document.querySelector(`#${view} [data-detail="${detailId}"]`)?.focus({preventScroll:true}));
  render();
})();
