(() => {
'use strict';
const data=window.PORTFOLIO_SYSTEMS,choose=document.querySelector('#system-choice'),states=document.querySelector('#state-choice'),box=document.querySelector('#specimen'),preview=document.querySelector('#lab-preview');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state='default',value='',busy=false,timer=0;
const initial=new URLSearchParams(location.search).get('project');if(data.some(p=>p.id===initial))choose.value=initial;
function luminance(hex){const rgb=hex.replace('#','').match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];}
function ratio(a,b){const x=luminance(a),y=luminance(b);return ((Math.max(x,y)+.05)/(Math.min(x,y)+.05)).toFixed(2);}
function announce(t){document.querySelector('#lab-status').textContent=t;}
function renderForm(){
 states.value=state;
 if(state==='success'){box.innerHTML=`<div class="specimen-card"><p class="specimen-eyebrow">A REVERSIBLE RESULT</p><h2>A little clarity,<br>kept.</h2><dl class="specimen-receipt"><dt>Your sample label</dt><dd>${escape(value||'My considered collection')}</dd></dl><p>Saved in this specimen for this visit.</p><button class="specimen-button outline" id="undo-sample" type="button">Undo this save</button></div>`;return;}
 box.innerHTML=`<form class="specimen-card" id="sample-form" novalidate><p class="specimen-eyebrow">A PATTERN FOR CLEAR FEEDBACK</p><h2>Give this collection<br>a useful name.</h2><label for="sample-name">Collection name</label><input id="sample-name" name="name" value="${escape(value)}" maxlength="60" aria-invalid="${state==='error'}" aria-describedby="sample-help${state==='error'?' sample-error':''}" ${state==='disabled'?'disabled':''}><p id="sample-help">Use a name you will recognize. This stays inside the demonstration.</p>${state==='error'?'<p class="sample-error" id="sample-error" role="alert">Enter a name before saving your collection.</p>':''}${state==='disabled'?'<p class="sample-error">Saving is unavailable in this inspected state. Choose “Ready for input” to continue.</p>':''}<button class="specimen-button" type="submit" ${state==='disabled'||busy?'disabled':''}>${busy?'Saving…':'Save sample collection'}</button></form>`;
 const form=document.querySelector('#sample-form');form.addEventListener('submit',e=>{e.preventDefault();if(busy||state==='disabled')return;value=document.querySelector('#sample-name').value.trim();if(!value){state='error';renderForm();document.querySelector('#sample-name').focus();announce('Enter a name before saving.');return;}busy=true;renderForm();announce('Saving the local sample.');timer=setTimeout(()=>{busy=false;state='success';renderForm();document.querySelector('#undo-sample').focus();announce('Sample saved. Undo is available.');},450);});
}
function renderSystem(){const p=data.find(x=>x.id===choose.value)||data[0];Object.entries(p.tokens).forEach(([k,v])=>preview.style.setProperty(k,v));document.querySelector('#lab-brand').textContent=p.name;document.querySelector('#lab-type').textContent=p.type;document.querySelector('#lab-ui').textContent=p.ui;document.querySelector('#lab-motion').textContent=p.motion;document.querySelector('#lab-product').href='experiences/'+p.id+'.html';document.querySelector('#lab-tokens').innerHTML=['--accent','--paper','--ink','--signal','--line'].map(k=>`<div><span style="background:${p.tokens[k]}"></span><b>${k.replace('--','')}</b><code>${p.tokens[k]}</code></div>`).join('');document.querySelector('#lab-contrast').innerHTML=`<p><b>${ratio(p.tokens['--ink'],p.tokens['--paper'])}:1</b> Text / paper</p><p><b>${ratio('#ffffff',p.tokens['--accent'])}:1</b> White / primary action</p><p><b>${ratio(p.tokens['--ink'],p.tokens['--signal'])}:1</b> Text / accent surface</p>`;document.querySelector('#lab-code').textContent=`body[data-app="${p.id}"] {\n${Object.entries(p.tokens).filter(([k])=>k.startsWith('--')).map(([k,v])=>'  '+k+': '+v+';').join('\n')}\n}`;renderForm();}
choose.addEventListener('change',()=>{clearTimeout(timer);busy=false;renderSystem();announce('Visual identity changed. Interaction state preserved.');});
states.addEventListener('change',()=>{clearTimeout(timer);busy=false;value=document.querySelector('#sample-name')?.value||value;state=states.value;renderForm();announce('Inspecting '+states.selectedOptions[0].textContent+'.');});
box.addEventListener('click',e=>{if(e.target.closest('#undo-sample')){clearTimeout(timer);busy=false;state='default';renderForm();document.querySelector('#sample-name').focus();announce('Save undone. Your text remains available to edit.');}});
document.querySelector('#copy-tokens').addEventListener('click',async()=>{const status=document.querySelector('#copy-status'),code=document.querySelector('#lab-code');try{await navigator.clipboard.writeText(code.textContent);status.textContent='Token CSS copied.';}catch{status.textContent='Clipboard access is unavailable. Select and copy the code above.';code.focus();}});
renderSystem();
})();
