window.AfterformData={
services:[
{id:'patch',code:'M01',title:'A hole or worn patch',group:'Repair',plain:'Fabric has worn thin or opened up.',from:24,to:46,finishes:['blend','visible','advise'],prompt:'Where is the worn area?',detail:'Start with the place that needs attention. Reinforcement and finish depend on the cloth and the size of the area.'},
{id:'seam',code:'M02',title:'A seam coming undone',group:'Repair',plain:'Two pieces of fabric are separating.',from:16,to:28,finishes:['blend','advise'],prompt:'Which seam has opened?',detail:'The studio would check the original stitching and the strength of the surrounding cloth before proposing a repair.'},
{id:'zip',code:'F01',title:'A zip that won’t work',group:'Repair',plain:'Stuck teeth, a broken pull or an opening zip.',from:30,to:58,finishes:['blend','advise'],prompt:'Where is the zip?',detail:'A replacement is not always the first answer. The slider, teeth and fabric need an assessment before the part is confirmed.'},
{id:'button',code:'F02',title:'A missing button',group:'Repair',plain:'One fastening makes all the difference.',from:10,to:22,finishes:['blend','visible','advise'],prompt:'Which fastening needs attention?',detail:'Tell the studio whether keeping a close match matters, or whether a deliberate contrast would suit the garment.'},
{id:'hem',code:'A01',title:'A length to adjust',group:'Adjust',plain:'Trousers, sleeves or a hem need a different length.',from:22,to:42,finishes:['blend','advise'],prompt:'Which edge needs adjusting?',detail:'A fitting or confirmed measurement is needed before cutting. This request records the intention, not a cutting instruction.'},
{id:'assess',code:'Q01',title:'Help me work it out',group:'Assessment',plain:'You don’t need the technical name.',from:null,to:null,finishes:['advise'],prompt:'What have you noticed?',detail:'Describe what you notice or bring the garment for an assessment. Uncertainty is a useful starting point.'}
],
garments:['Shirt','Knitwear','Jeans','Trousers','Jacket','Dress','Something else'],
materials:['Cotton or linen','Denim','Wool or knit','Mixed fibres','Not sure'],
areas:['Front or back','Elbow or sleeve','Knee or seat','Side seam','Fastening','Hem or edge','Not sure'],
finishes:{blend:{title:'Keep it quiet',short:'Closest practical match',copy:'Ask for a finish that blends with the garment. An invisible result is not guaranteed.'},visible:{title:'Make it part of the piece',short:'Visible contrast',copy:'Let a contrasting patch, thread or fastening become an intentional detail.'},advise:{title:'Let’s decide together',short:'Studio advice',copy:'Keep your options open until the material and damage have been assessed.'}},
passports:[
{id:'AF-S01',name:'The everyday shirt',garment:'Cotton work shirt',code:'M01',area:'Elbow',finish:'Visible patch · vermilion',record:'Illustrative repair record: a contrasting reinforcement patch at the elbow, with the original garment label retained.',image:'repair-editorial',next:'Check the original care label before washing. The sample repair record does not replace garment-specific care instructions.'},
{id:'AF-S02',name:'The familiar jeans',garment:'Indigo denim',code:'M01',area:'Worn panel',finish:'Visible darn · lilac',record:'Illustrative repair record: a controlled lilac darning area reinforces a worn panel of denim.',image:'denim-detail',next:'Keep this record with the garment. If the edge loosens, describe the location when requesting another assessment.'},
{id:'AF-S03',name:'The borrowed jacket',garment:'Woven jacket',code:'F02',area:'Front fastening',finish:'Closest practical match',record:'Illustrative repair record: one replacement fastening, with the remaining original buttons kept.',image:null,next:'Retain any spare fastening with this record. Material and care information must be checked on the original label.'}
]};
