(()=>{'use strict';const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pieces={shirt:['AF-S01','M01','The everyday shirt','Elbow / visible patch'],jeans:['AF-S02','M01','The familiar jeans','Worn panel / lilac darn'],jacket:['AF-S03','F02','The borrowed jacket','Front fastening / closest match']};
const states={review:['01','Needs review','Read scope, finish and price.'],changed:['02','Scope changed','Review the revised proposal.'],agreed:['03','Agreement recorded','Match the approved revision.'],ready:['04','Ready to collect','Match the garment and record.']};
function label(){const piece=pieces[$('#label-piece').value],state=states[$('#label-state').value],long=$('#label-long').checked,mono=$('#label-mono').checked,el=$('#label-proof');el.className='label-proof '+(long?'extended':'standard')+(mono?' monochrome':'')+' state-'+$('#label-state').value;el.innerHTML=`<div class="label-state"><span>${state[0]}</span><strong>${state[1]}</strong></div><div class="label-id"><b>${long?'AF-X01':piece[0]}</b><span>${long?'F02':piece[1]}</span></div><h3>${esc(long?'The indigo work jacket with its original brass fastenings':piece[2])}</h3><p>${long?'Front fastening / replacement to be discussed':piece[3]}</p><div class="label-next">${state[2]}</div><footer>${long?'CONTENT STRESS SPECIMEN':'ILLUSTRATIVE WORKFLOW'} / REV 01</footer>`;$('#label-size').textContent=long?'Extended tag · 72 × 115 mm':'Work label · 90 × 65 mm';$('#label-explanation').textContent=long?'Long descriptions move to a taller tag. Type is not reduced to force the content into the short format. This is a separate content-stress specimen.':'The ID, plain-language description and next action stay in fixed zones. Status is written out; colour is supplementary.';$('#label-announcer').textContent=state[1]+'. '+(mono?'Monochrome. ':'')+(long?'Extended tag selected.':'Work label selected.')}
['label-piece','label-state','label-long','label-mono'].forEach(id=>$('#'+id).addEventListener('change',label));$('#print-label').addEventListener('click',()=>{document.body.classList.add('print-label-mode');window.print()});window.addEventListener('afterprint',()=>document.body.classList.remove('print-label-mode'));label();
const contexts={masthead:['144','Primary wordmark at its digital minimum target.'],lockup:['220','Service lockup keeps the descriptor legible.'],avatar:['48','Compact letters belong in an avatar, next to the full brand name.'],micro:['24','The joining symbol removes fine letterforms at small sizes.']},assets={masthead:'assets/wordmark-plum.svg',lockup:'assets/system/lockup-horizontal.svg',avatar:'assets/system/avatar.svg',micro:'assets/system/micro-mark.svg'};
$('#logo-context').addEventListener('change',e=>{const k=e.target.value;$('#responsive-logo').src=assets[k];$('#responsive-logo').style.width=contexts[k][0]+'px';$('#logo-explanation').textContent=contexts[k][1]});
let timer=null;const stage=$('#motion-stage'),play=$('#play-brand-motion'),stop=$('#stop-brand-motion');function settle(msg){if(timer!==null)clearTimeout(timer);timer=null;stage.classList.remove('is-playing');stage.classList.add('is-settled');play.disabled=false;stop.disabled=true;$('#motion-state').textContent=msg}
play.addEventListener('click',()=>{const reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce){settle('Reduced motion: the finished composition is shown immediately.');return}stage.classList.remove('is-settled');stage.classList.add('is-playing');play.disabled=true;stop.disabled=false;$('#motion-state').textContent='The joining line reveals once, then settles.';timer=setTimeout(()=>settle('Finished. The mark stays still until you play it again.'),1200)});stop.addEventListener('click',()=>settle('Stopped. The finished composition stays visible.'));
})();
