(() => {
const p=new URLSearchParams(location.search),project=p.get('project')||'aurea',compact=p.get('compact')==='1';
const catalog={
holland:{name:'Holland Walking Tour',mobile:'walk',screens:[['discover','Discovery','Readable route cards show time, stop count, and unverified access details before starting.'],['builder','Build a walk','Selectable story stops retain explicit checkbox states and prevent an empty preview.'],['detail','Route preview','A clear itinerary pairs practical commitments with a numbered story sequence.'],['walk','Active walk','Progress, pause and one next action support a focused walking experience.'],['story','Story detail','A generous reading column and pull quote give local storytelling room to breathe.'],['complete','Completion','The finished state closes the route and offers another walk.'],["tools", "Walk tools", "Larger text throughout the guide, reduced movement, and simple help keep the experience approachable."],["cms", "Content studio", "Reusable stories and route review states restore the service behind the visitor experience."],["stops", "Story library", "A shared library links sample story records to the reading experience."],["archive", "Visual archive", "Credited Holland photography and its use remain traceable."]]},
imhere:{name:'ImHere',mobile:'student',screens:[['faculty','Faculty overview','Live sample counts, a structured roster and correction controls share one clear workspace.'],['course','Course detail','Session control sits beside an accessible, explicitly illustrative attendance chart.'],['reviews','Review queue','Exceptions get a focused card with visible decision actions and shared record updates.'],['student','Student check-in','A compact class ticket gives the student a single primary action and a clear correction path.'],['history','Attendance history','A scan-friendly session history uses labels as well as color.'],["directory", "Class directory", "Student records connect attendance status with human review context."],["student-detail", "Student record", "A focused profile exposes current status and a clear correction path."],["excuse", "Correction request", "A validated explanation moves into the same faculty review queue."]]},
loopline:{name:'Loopline',mobile:'create',screens:[['dashboard','Partner overview','A confident green workspace separates the primary handoff action from current records.'],['create','Eligibility','Large radio cards provide a deliberate stopping point when eligibility is uncertain.'],['create&step=1','Food details','A concise form captures description and container count with validation.'],['create&step=2','Scheduling','Explicit pickup windows keep timing understandable before confirmation.'],['create&step=3','Review','An aligned review screen gathers the details into one readable handoff summary.'],['confirmed','Confirmation','The receipt distinguishes a saved local sample from real partner coordination.'],['schedule','Schedule','Time windows and sample records remain visible in a calm operational view.'],["tracking", "Handoff journey", "Manual stage progression demonstrates a clear service continuation without claiming live tracking."]]},
nutriva:{name:'Nutriva',mobile:'inventory-review',screens:[['tonight','Meal discovery','Photographic recipe cards connect dinner ideas to the ingredients already in the pantry.'],['recipe','Recipe detail','Food imagery, concise metadata and ingredient availability support the next decision.'],['pantry','Pantry','Editable inventory has duplicate protection and immediately updates meal matches.'],['plan','Weekly plan','A flexible collection of meals produces a connected grocery list.'],['grocery','Grocery list','Missing ingredients are deduplicated and can be checked off independently.'],["inventory-review", "Inventory review", "Uncertain ingredient suggestions are confirmed or skipped before changing pantry matches."],["saved", "Recipe box", "A dedicated place keeps saved meals separate from the weekly plan."],["cook", "Cooking mode", "A focused step-by-step preparation walkthrough restores the cooking experience."]]},
novella:{name:'Novella',mobile:'reader',screens:[['discover','Discovery','Mood chips and an editorial collection create a quieter way into reading.'],['book','Book detail','Original cover concepts, a sample line and a clear reading action introduce each story.'],['reader','Reading room','A distraction-light reading page supports adjustable type and dark mode.'],['library','Personal library','Saved titles stay in one considered collection with a useful empty state.'],["desk", "The reading desk", "A personal reading desk brings the current book, opening line, and reading controls together."]]},
aurea:{name:'Áurea',mobile:'detail',screens:[['discover','Scent discovery','Search the perfume database, filter by family or note, and compare structured records.'],['finder','Scent finder','Three expressive preference cards provide an approachable, editable starting point.'],['results','Your match','The recommendation explains its relationship to the selected preference.'],['detail','Fragrance detail','A perfume dossier makes notes browsable and separates record information from personal wear notes.'],['compare','Comparison','Aligned profiles support judgment without invented performance scores.'],['archive','Personal archive','Saved scents connect to a personal collection and a session-only wear journal.'],['journal','Wear journal','A short, labeled form captures an impression with validation and confirmation.'],["evolution", "Scent structure", "Opening, heart, and base notes receive a full editorial composition without false performance precision."],["sampling", "Sampling ritual", "A personal reflection checklist connects exploration to the wear journal."]]}
};catalog.aurea.screens.push(['notes','Note index','An alphabetical note directory links directly to the perfumes that include each note.']);catalog.imhere.screens.push(['verification','Check-in consent','Review the session and verification boundary before updating the sample record.'],['audit','Record history','Faculty decisions retain the previous status, resulting change and explanation.'],['correction','Explained correction','A required reason connects the proposed change to the shared attendance record.']);catalog.novella.screens.push(['blind','Read without the cover','Try the voice first, then reveal the book.'],['passages','Saved passages','Keep and revisit original opening passages in a private session collection.']);const c=catalog[project];if(!c)return;
const directions={holland:{word:'HOLLAND WALKS',line:'Your walk.<br>Your pace.',detail:'Holland, Michigan / A welcoming walking guide',asset:'holland-place.webp'},imhere:{word:'IMHERE',line:'One record.<br>Two perspectives.',detail:'Navy / Burnt orange / Human clarity'},loopline:{word:'LOOPLINE',line:'PACK. LABEL.<br>HAND OFF.',detail:'Kitchen to community',asset:'loopline-field-kit.webp'},nutriva:{word:'nutriva',line:'Use what<br>you have.',detail:'Recipe box / Pantry / Everyday kitchen',asset:'nutriva-kitchen-kit.webp'},novella:{word:'novella',line:'A place<br>to linger.',detail:'The reading edition / Volume 01',asset:'novella-the-light-between-streets.webp'},aurea:{word:'áurea',line:'Follow<br>the notes.',detail:'A perfume database / The discovery edit',asset:'aurea-santal-dusk.webp'}};const direction=directions[project];

document.body.dataset.project=project;document.body.classList.toggle('compact',compact);document.title=c.name+' — Screen & Mockup Studio';
let index=Math.max(0,c.screens.findIndex(s=>s[0]===p.get('view'))),device=innerWidth<600?'mobile':'desktop',state='default';
const stage=document.querySelector('#showcase');
const src=(view)=>`${project}.html?embed=1&scene=1&view=${view}${state==='default'?'':'&state='+state}`;
function render(){const s=c.screens[index];stage.innerHTML=`<header class="viewer-head"><div><p>UI screens / Live design studio</p><h1>${c.name}</h1></div><a href="${project}.html" target="_top">Try the connected prototype ↗</a></header><nav class="screen-nav" aria-label="Screen gallery">${c.screens.map((s,i)=>`<button data-screen="${i}" ${i===index?'aria-current="page"':''}>${String(i+1).padStart(2,'0')} ${s[1]}</button>`).join('')}</nav><div class="viewer-tools"><div class="device-switch" role="group" aria-label="Preview viewport">${['desktop','tablet','mobile'].map(d=>`<button data-device="${d}" aria-pressed="${d===device}">${d[0].toUpperCase()+d.slice(1)}</button>`).join('')}</div><label>State <select id="state"><option value="default">Populated sample</option>${['aurea','novella','nutriva'].includes(project)?'<option value="empty">Empty collection</option>':''}${project==='imhere'?'<option value="success">Check-in success</option><option value="closed">Session closed</option>':''}${project==='holland'?'<option value="paused">Paused walk</option>':''}${project==='novella'?'<option value="night">Dark reading page</option>':''}</select></label></div><div class="stage">${compact?`<div class="board-identity"><span>${direction.word}</span><h2>${direction.line}</h2><p>${direction.detail}</p></div>${direction.asset?`<img class="board-art" src="${direction.asset.startsWith('../')?direction.asset:'../assets/'+direction.asset}" alt="" aria-hidden="true">`:''}`:''}<div class="display main-display"><div class="screen-chrome"><span class="chrome-back">‹ ›</span><span class="chrome-title">${c.name.toUpperCase()} / ${s[1].toUpperCase()}</span><span>↗</span></div><iframe src="${src(s[0])}" title="${c.name}: ${s[1]}" ${compact?'tabindex="-1" inert':''}></iframe></div>${compact?`<div class="display mobile-display secondary-display"><div class="screen-chrome"><span class="chrome-title">${c.name.toUpperCase()}</span></div><iframe src="${src(c.mobile)}" title="${c.name} mobile interface" tabindex="-1" inert></iframe></div><span class="board-label">${c.name} / Product & visual system</span>`:''}</div><div class="viewer-caption"><p>${s[2]}</p><span>Actual HTML/CSS interface · Sample content</span></div>`;const select=document.querySelector('#state');select.value=state;select.onchange=()=>{state=select.value;const target=state==='night'?'reader':state==='success'||state==='closed'?'student':state==='paused'?'walk':state==='empty'?project==='nutriva'?'plan':project==='novella'?'library':'archive':null;if(target){const i=c.screens.findIndex(s=>s[0]===target);if(i>=0)index=i;}render();};scale();}
function scale(){const box=document.querySelector('.stage'),w=box.clientWidth,main=document.querySelector('.main-display');if(compact){box.style.height=w*.64+'px';let mw=1100,mh=770,mx=.045,my=.045,ms=.79/1100,pw=390,ph=790,px=.72,py=.12,ps=.245/390,mr=0,pr=0;
if(project==='holland'){mw=390;mh=810;mx=.335;my=.06;ms=.30/390;px=.665;py=.105;ps=.28/390;pr=2;main.classList.add('mobile-display');}
if(project==='imhere'){mx=.20;my=.075;ms=.75/1100;px=.04;py=.19;ps=.22/390;}
if(project==='loopline'){mx=.045;my=.075;ms=.71/1100;px=.725;py=.13;ps=.23/390;}
if(project==='nutriva'){mx=.045;my=.055;ms=.73/1100;px=.725;py=.105;ps=.23/390;mr=-1;pr=2;}
if(project==='novella'){mw=1000;mh=730;mx=.045;my=.095;ms=.68/1000;px=.735;py=.14;ps=.22/390;}
if(project==='aurea'){mx=.045;my=.07;ms=.74/1100;px=.73;py=.10;ps=.23/390;mr=-1.5;pr=3;}
Object.assign(main.style,{width:mw+'px',height:mh+'px',left:w*mx+'px',top:w*my+'px',transform:`scale(${w*ms}) rotate(${mr}deg)`});const phone=document.querySelector('.secondary-display');Object.assign(phone.style,{width:pw+'px',height:ph+'px',left:w*px+'px',top:w*py+'px',transform:`scale(${w*ps}) rotate(${pr}deg)`});
}else{const width=device==='mobile'?390:device==='tablet'?768:1100,height=device==='mobile'?790:device==='tablet'?820:760,ratio=Math.min((w-36)/width,1);box.style.height=height*ratio+25+'px';main.classList.toggle('mobile-display',device==='mobile');Object.assign(main.style,{width:width+'px',height:height+'px',left:(w-width*ratio)/2+'px',top:'0',transform:`scale(${ratio})`});}}
stage.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.screen!==undefined){index=Number(b.dataset.screen);state='default';render();}if(b.dataset.device){device=b.dataset.device;render();}});render();new ResizeObserver(scale).observe(stage);
})();
