/* Original sample programme. All sessions, rooms and availability are fictional. */
window.IntervalData = {
  days: ['Saturday','Sunday'],
  rooms: {'01': {name:'Listening room', note:'Seated · steady light', direction:'Left from the welcome desk'}, '02': {name:'Studio',note:'Seating varies by session · daylight',direction:'Straight ahead from the welcome desk'},'03':{name:'Black box',note:'Seated · dim light',direction:'Right from the welcome desk'}},
  sessions: [
    {id:'deep-listening',title:'Deep listening',day:'Saturday',start:'11:00',end:'11:45',room:'01',type:'Spoken',image:'listening-room',seated:true,light:'Steady light',sound:'Speaking voice with short, unamplified demonstrations.',intro:'A gentle place to begin. Notice the sounds already around you, and learn a different way to pay attention.',description:'A guided introduction to focused listening, with time for quiet observation and an optional conversation. No musical knowledge or participation is required.',format:'Guided listening + conversation',full:false},
    {id:'objects-in-motion',title:'Objects in motion',day:'Saturday',start:'11:20',end:'12:10',room:'02',type:'Acoustic',image:'strings-detail',seated:true,light:'Daylight',sound:'Unamplified strings and small resonant objects; occasional sharper sounds.',intro:'Wood, wire and the space between. An intimate exploration of how ordinary materials become instruments.',description:'A close listening session built around string resonance and small acoustic objects. A short spoken introduction explains what will happen before the performance begins.',format:'Acoustic performance',full:false},
    {id:'tape-as-landscape',title:'Tape as landscape',day:'Saturday',start:'12:30',end:'13:20',room:'03',type:'Amplified',image:'tape-landscape',seated:true,light:'Dim, steady light',sound:'Amplified recorded sound with layered textures and changing volume.',intro:'Recorded fragments become a place to spend time. A slow-moving live tape composition.',description:'A listening performance shaped from loops, silence and recorded environmental textures. The programme includes amplified material; volume levels would need confirmation with the production team.',format:'Live tape performance',full:false},
    {id:'between-the-notes',title:'Between the notes',day:'Saturday',start:'14:00',end:'14:50',room:'02',type:'Acoustic',image:'strings-detail',seated:true,light:'Daylight',sound:'Unamplified bowed strings, with deliberate pauses.',intro:'A small room, a single instrument, and a little more space around every sound.',description:'An acoustic study in duration and restraint. This session demonstrates the full-capacity state: you can save your interest locally, but this prototype cannot reserve a seat or contact you.',format:'Acoustic performance',full:true},
    {id:'small-sounds',title:'Small sounds',day:'Sunday',start:'11:00',end:'11:45',room:'01',type:'Acoustic',image:'strings-detail',seated:true,light:'Steady light',sound:'Small acoustic sounds and spoken introductions.',intro:'Listen a little closer. An unhurried session about quiet materials and unexpected detail.',description:'A sequence of short acoustic studies, separated by pauses. Seating is provided in this fictional programme; audience access and sound levels would require a real venue assessment.',format:'Listening demonstration',full:false},
    {id:'hear-a-place',title:'How to hear a place',day:'Sunday',start:'11:15',end:'12:15',room:'02',type:'Spoken',image:'listening-room',seated:false,light:'Daylight',sound:'A facilitated conversation with short field-recording examples.',intro:'What does a room tell us before anyone speaks? A conversation about attention, place and sound.',description:'A participatory studio discussion with a mixture of standing and sitting. Participation is optional. Limited seating is a sample condition and can be excluded using the all-seated filter.',format:'Conversation + demonstration',full:false},
    {id:'after-the-signal',title:'After the signal',day:'Sunday',start:'13:00',end:'14:00',room:'03',type:'Amplified',image:'tape-landscape',seated:true,light:'Dim, steady light',sound:'Amplified tape, electronic tones and shifts in volume.',intro:'Follow a recorded sound as it changes, fades and returns in a new form.',description:'A live exploration of tape and electronic processing. No audio plays automatically in this prototype. The format and lighting notes support a more informed choice before adding the session.',format:'Electronic listening performance',full:false},
    {id:'room-for-listening',title:'A room for listening',day:'Sunday',start:'14:30',end:'15:30',room:'01',type:'Spoken',image:'listening-room',seated:true,light:'Steady light',sound:'A small-group conversation; no amplified performance.',intro:'Bring a question, or simply listen. An open conversation to close the weekend.',description:'A facilitated closing conversation on what we notice when we make time for listening. You can contribute, listen, arrive at the start and leave when you need to.',format:'Closing conversation',full:false}
  ]
};
