(() => {
'use strict';
const D = window.IntervalData, sessions=D.sessions, $=s=>document.querySelector(s), main=$('#main');
const key='interval-plan-v1', defaults={plan:[],interest:[],pass:null,large:false};
const study=((location.search||'').match(/[?&]study=(programme|detail|conflict|plan|alternatives|pass|room|empty)(?:&|$)/)||[])[1]||'';
let saved={}, storageOK=true;
try{if(!study)saved=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch(_){storageOK=false;}
if(study){saved={plan:['plan','alternatives'].includes(study)?['objects-in-motion','tape-as-landscape']:study==='conflict'?['deep-listening']:study==='pass'?['deep-listening','tape-as-landscape']:[],minBreak:30};if(study==='pass')saved.pass={name:'A curious listener',ids:[...saved.plan]};}
const valid=id=>sessions.some(s=>s.id===id), byId=id=>sessions.find(s=>s.id===id);
const unique=a=>[...new Set(Array.isArray(a)?a.filter(valid):[])];
const state={plan:unique(saved.plan).filter(id=>!byId(id).full),interest:unique(saved.interest),pass:null,large:!!saved.large,day:'Saturday',type:'All',query:'',seated:false,window:null,minBreak:[0,15,30].includes(saved.minBreak)?saved.minBreak:15,undo:null};
const minutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));
const overlap=(a,b)=>a.day===b.day&&minutes(a.start)<minutes(b.end)&&minutes(b.start)<minutes(a.end);
state.plan=state.plan.filter((id,i,a)=>!a.slice(0,i).some(x=>overlap(byId(id),byId(x))));
if(state.plan.length&&saved.pass&&typeof saved.pass.name==='string'&&Array.isArray(saved.pass.ids)&&saved.pass.ids.join('|')===state.plan.join('|'))state.pass={name:saved.pass.name.slice(0,50),ids:[...state.plan]};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const room=s=>D.rooms[s.room], clock=s=>`${s.start}–${s.end}`;
const ordered=ids=>ids.map(byId).sort((a,b)=>D.days.indexOf(a.day)-D.days.indexOf(b.day)||minutes(a.start)-minutes(b.start));
function persist(){if(study)return;try{localStorage.setItem(key,JSON.stringify({plan:state.plan,interest:state.interest,pass:state.pass,large:state.large,minBreak:state.minBreak}));}catch(_){storageOK=false;}}
function announce(message){$('#announcer').textContent='';setTimeout(()=>{$('#announcer').textContent=message;},40);}
function notify(message,undo=false){$('#notice').hidden=false;$('#notice').innerHTML=`<span>${esc(message)}</span>${undo?'<button data-action="undo">Undo</button>':''}<button data-action="dismiss" aria-label="Dismiss message">×</button>`;announce(message);}
function remember(){state.undo={plan:[...state.plan],pass:state.pass?{...state.pass,ids:[...state.pass.ids]}:null};}
function commit(message){state.pass=null;persist();render(false);notify(message,true);}
function go(path){if(location.hash==='#'+path)render(true);else location.hash=path;}
function actionButton(s){if(s.full)return '<button class="button disabled" disabled>Full · sample status</button>';const added=state.plan.includes(s.id);return `<button class="button ${added?'added':'primary'}" data-action="${added?'remove':'add'}" data-id="${s.id}">${added?'✓ In my plan · Remove':'+ Add to my plan'}</button>`;}
function row(s){const added=state.plan.includes(s.id);return `<article class="session-row"><div class="session-time"><time>${s.start}</time><span>— ${s.end}</span><small>${s.day}</small></div><a class="session-name" href="#session/${s.id}"><span class="overline">${s.type} / ROOM ${s.room}</span><h3>${s.title}<span aria-hidden="true">↗</span></h3><p>${s.format}</p></a><div class="session-conditions"><span>${s.seated?'All seated':'Mixed standing / seating'}</span><span>${s.light}</span>${s.full?'<b>Full · sample status</b>':''}</div><div class="row-action">${s.full?`<a class="button" href="#session/${s.id}">View session</a>`:`<button class="small-button ${added?'is-selected':''}" data-action="${added?'remove':'add'}" data-id="${s.id}" aria-label="${added?'Remove':'Add'} ${s.title} ${added?'from':'to'} my plan">${added?'✓ Added':'Add +'}</button>`}</div></article>`;}
function results(){const q=state.query.toLowerCase().trim();return sessions.filter(s=>s.day===state.day&&(state.type==='All'||s.type===state.type)&&(!state.seated||s.seated)&&(!state.window||(s.start>=state.window.start&&s.end<=state.window.end))&&(!q||`${s.title} ${s.intro} ${s.format}`.toLowerCase().includes(q)));}
function filterChips(){return `<div class="active-filters" aria-label="Applied filters">${state.query?`<button data-action="clear-query" aria-label="Remove search ${esc(state.query)}">Search: ${esc(state.query)} <span aria-hidden="true">×</span></button>`:''}${state.type!=='All'?`<button data-action="clear-type">${state.type} <span aria-hidden="true">×</span></button>`:''}${state.seated?'<button data-action="clear-seated">All seated <span aria-hidden="true">×</span></button>':''}${state.window?`<button data-action="clear-window">${state.window.start}–${state.window.end} <span aria-hidden="true">×</span></button>`:''}</div>`;}
function resultMarkup(){const list=results();const filtered=state.query||state.type!=='All'||state.seated||state.window;return `${filterChips()}<div class="results-caption"><p id="result-count">${list.length} ${list.length===1?'session':'sessions'} / ${state.day}</p>${filtered?'<button class="text-button" data-action="clear-filters">Clear all filters</button>':''}</div>${list.length?list.map(row).join(''):'<div class="empty"><h3>No sessions fit these choices.</h3><p>Remove one filter above, or start again with this day. Your personal plan is kept.</p><button class="button primary" data-action="clear-filters">Show this day’s programme</button></div>'}`;}
function programme(){return `<section class="programme-intro content"><div><span class="overline">INTERVAL / A FESTIVAL FOR CLOSE LISTENING</span><h1>Find your <em>interval.</em></h1><p>Choose a sound. Check the setting. Leave a little space.</p></div><a class="guide-callout" href="guide.html"><img class="mini-book-mark" src="assets/print/guide-01.webp" alt=""><span>Take the pocket guide<br><small>Programme, rooms & a place to pause ↗</small></span></a></section><section class="programme content" id="programme-list"><div class="programme-tools"><div class="day-tabs" aria-label="Programme day">${D.days.map(d=>`<button data-day="${d}" aria-pressed="${d===state.day}">${d}<span>${d==='Saturday'?'01':'02'}</span></button>`).join('')}</div><a class="text-button" href="#rooms">Find a room ↗</a></div><form class="filters" role="search" id="search-form"><label class="search-label">Find a session<input id="session-search" type="search" value="${esc(state.query)}" placeholder="Try tape, strings or conversation" autocomplete="off"></label><label>Experience<select id="experience-filter">${['All','Spoken','Acoustic','Amplified'].map(t=>`<option ${state.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="check-label"><input type="checkbox" id="seated-filter" ${state.seated?'checked':''}>All-seated sessions</label></form><details class="visit-window" ${state.window?'open':''}><summary>Fit sessions around your visit ${state.window?`<span>${state.window.start}–${state.window.end}</span>`:''}</summary><form id="window-form" novalidate><p>Show sessions you can attend from start to finish.</p><div><label>Arriving at<input type="time" id="arrival-time" value="${state.window?.start||'11:00'}" aria-describedby="window-error"></label><label>Leaving by<input type="time" id="leaving-time" value="${state.window?.end||'15:30'}" aria-describedby="window-error"></label><button class="button primary" type="submit">Apply time window</button>${state.window?'<button class="text-button" type="button" data-action="clear-window">Remove time window</button>':''}</div><p id="window-error" class="form-error" role="alert" hidden></p></form></details><div id="session-results">${resultMarkup()}</div><div class="programme-note"><p>Read each session’s seating, lighting and sound notes before choosing. This is an original sample programme for a fictional venue.</p><a href="#access">Plan your visit ↗</a></div></section><section class="quiet-editorial"><img src="assets/listening-room.webp" alt="Illustrative intimate listening room" loading="lazy"><div><span class="overline">THE IDEA BEHIND INTERVAL</span><h2>Make space<br>for listening.</h2><p>For the sound. For the silence.<br>For something new.</p><a href="guide.html">Open the listening guide ↗</a></div></section>`;}
function detail(id){const s=byId(id);if(!s)return `<section class="content empty"><h1>Session not found.</h1><p>This link doesn’t match the sample programme.</p><a class="button primary" href="#programme">Back to the programme</a></section>`;return `<section class="detail-top content"><a class="back" href="#programme">← The programme</a><div class="detail-grid"><div class="detail-copy"><span class="overline">${s.type} / ${s.format}</span><h1>${s.title}</h1><p class="intro">${s.intro}</p><dl class="session-facts"><div><dt>When</dt><dd>${s.day}<br>${clock(s)}</dd></div><div><dt>Where</dt><dd><a href="#room/${s.room}">Room ${s.room}<br>${room(s).name} ↗</a></dd></div><div><dt>Duration</dt><dd>${minutes(s.end)-minutes(s.start)} minutes</dd></div></dl><div class="detail-actions">${actionButton(s)}<a class="text-button" href="#plan">View my plan ↗</a></div>${s.full?`<p class="small">Full is an example availability state. No seat can be reserved.</p><button class="button" data-action="interest" data-id="${s.id}">${state.interest.includes(s.id)?'✓ Interest saved · Remove':'Save my interest locally'}</button>`:''}</div><figure class="detail-image"><img src="assets/${s.image}.webp" alt="${s.image==='strings-detail'?'Illustrative close-up of acoustic strings and wood':s.image==='tape-landscape'?'Illustrative analog tape equipment':'Illustrative listening room'}"><figcaption>ILLUSTRATIVE ART DIRECTION / ${s.type.toUpperCase()}</figcaption></figure></div></section><section class="content detail-bottom"><div><span class="overline">WHAT TO EXPECT</span><h2>A little context.<br>A better choice.</h2><p>${s.description}</p></div><div class="conditions-panel"><h2>Before you choose</h2><dl><div><dt>Seating</dt><dd>${s.seated?'All-seated session':'Mixed standing and limited seating'}</dd></div><div><dt>Lighting</dt><dd>${s.light}. No flashing light is specified in this sample.</dd></div><div><dt>Sound</dt><dd>${s.sound}</dd></div><div><dt>Taking a break</dt><dd>The concept allows leaving and re-entering between sections; a real event would confirm this with its team.</dd></div></dl><a class="text-button" href="#access">Room and visit information ↗</a></div></section>`;}
function planRows(ids){return D.days.map(day=>{const list=ordered(ids).filter(s=>s.day===day);return list.length?`<section class="plan-day"><h2>${day}<span>${list.length} ${list.length===1?'session':'sessions'}</span></h2>${list.map((s,i)=>{const gap=i?minutes(s.start)-minutes(list[i-1].end):0;const short=i&&gap<state.minBreak;return `${i?`<div class="break-label ${short?'short-break':''}"><span>${gap} minutes between sessions</span>${short?`<p>${state.minBreak-gap} minutes less than your preferred ${state.minBreak}-minute break.</p><div class="break-options"><a href="#alternatives/${list[i-1].id}">Change ${list[i-1].title} ↗</a><a href="#alternatives/${s.id}">Change ${s.title} ↗</a></div>`:''}</div>`:''}<article class="plan-row"><div><span class="overline">${clock(s)}</span><h3><a href="#session/${s.id}">${s.title} ↗</a></h3><p>${s.type} · ${s.seated?'All seated':'Mixed seating'}</p><a class="room-tag" href="#room/${s.room}" aria-label="Open Room ${s.room}: ${room(s).name}"><b>${s.room}</b><span>${room(s).name}</span><span aria-hidden="true">↗</span></a></div><button class="text-button" data-action="remove" data-id="${s.id}" aria-label="Remove ${s.title} from my plan">Remove</button></article>`;}).join('')}</section>`:'';}).join('');}
function plan(){return `<section class="content inner-page"><div class="page-heading"><span class="overline">A PROGRAMME WITH ROOM TO BREATHE</span><h1>Your kind<br>of <em>weekend.</em></h1><p>Your choices are saved in this browser${storageOK?'.':' for this visit only; persistent storage is unavailable.'} This is a personal plan, not a reservation.</p></div>${state.plan.length?`<div class="plan-layout"><div><div class="break-preference"><label for="break-preference">Space between sessions</label><select id="break-preference">${[0,15,30].map(n=>`<option value="${n}" ${n===state.minBreak?'selected':''}>${n===0?'No minimum':n+' minutes preferred'}</option>`).join('')}</select><p>A planning preference, not an estimate of walking time. Short breaks stay visible so you can decide.</p></div>${planRows(state.plan)}</div><aside class="plan-summary"><span class="overline">YOUR PLAN</span><strong>${state.plan.length.toString().padStart(2,'0')}</strong><p>${state.plan.length===1?'session':'sessions'} / no overlapping times</p><a class="button primary" href="#review">Make a sample pass ↗</a><button class="text-button" data-action="download-plan">Download plain-text plan ↓</button><a class="text-button" href="#programme">Keep exploring</a><p class="small">Keep a readable copy for later. No seat is held and no payment is taken.</p></aside></div>`:`<div class="empty plan-empty"><span aria-hidden="true">( &nbsp; )</span><h2>Leave room for something new.</h2><p>Choose a session from the programme. We’ll show you if two choices happen at the same time.</p><a class="button primary" href="#programme">Explore the programme ↗</a></div>`}${state.interest.length?`<section class="interest-list"><h2>Saved interest</h2><p>These full sessions are separate from your plan. No waitlist request has been sent.</p>${state.interest.map(id=>`<div><a href="#session/${id}">${byId(id).title} ↗</a><button class="text-button" data-action="interest" data-id="${id}">Remove interest</button></div>`).join('')}</section>`:''}<div class="plan-bottom-links"><a href="guide.html">Browse the pocket guide ↗</a><a href="#rooms">See the room directory ↗</a></div></section>`;}
function fits(s,others){return others.every(o=>o.day!==s.day||(!overlap(s,o)&&(minutes(s.start)>=minutes(o.end)?minutes(s.start)-minutes(o.end):minutes(o.start)-minutes(s.end))>=state.minBreak));}
function alternatives(id){const current=byId(id);if(!current||!state.plan.includes(id))return `<section class="content empty"><h1>Return to your plan.</h1><p>This session is no longer in your current choices.</p><a class="button primary" href="#plan">Open my plan</a></section>`;const others=state.plan.filter(x=>x!==id).map(byId);const options=sessions.filter(s=>s.day===current.day&&s.id!==id&&!s.full&&!state.plan.includes(s.id)&&fits(s,others));return `<section class="content inner-page"><a class="back" href="#plan">← Keep my current plan</a><div class="page-heading"><span class="overline">A LITTLE MORE BREATHING ROOM</span><h1>Another way<br>to spend the <em>day.</em></h1><p>Alternatives to <b>${current.title}</b> on ${current.day}. These fit around your other choices with at least ${state.minBreak} minutes between sessions.</p></div><div class="replacement-summary"><span>YOUR CURRENT CHOICE</span><strong>${current.title}</strong><span>${clock(current)} / Room ${current.room}</span><p>Your plan stays as it is until you choose a replacement.</p></div><div class="alternative-list">${options.length?options.map(s=>`<article><div><span class="overline">${clock(s)} / ROOM ${s.room} / ${s.type}</span><h2><a href="#session/${s.id}">${s.title} ↗</a></h2><p>${s.intro}</p></div><button class="button primary" data-action="use-alternative" data-from="${id}" data-id="${s.id}">Replace with this session</button></article>`).join(''):`<div class="empty"><h2>No compatible alternatives.</h2><p>You can keep your choices, remove a session or adjust your break preference in My plan.</p><a class="button primary" href="#plan">Back to my plan</a></div>`}</div></section>`;}
function roomDiagram(selected=''){return `<div class="room-schematic" aria-label="Conceptual room directory; not a measured floor plan"><div class="room-nodes">${Object.entries(D.rooms).map(([n,r])=>`<a href="#room/${n}" ${n===selected?'aria-current="page"':''}><span>ROOM</span><b>${n}</b><strong>${r.name}</strong><small>${n==='01'?'← Left':n==='02'?'↑ Ahead':'Right →'}</small></a>`).join('')}</div><div class="welcome-node"><span>START HERE</span><b>Welcome desk</b></div><p>Concept schematic · no scale, distances or verified access route</p></div>`;}
function rooms(id){const r=D.rooms[id];if(id&&!r)return `<section class="content empty"><h1>Room not found.</h1><p>Use the three-room directory to find the right guide.</p><a class="button primary" href="#rooms">Open the directory</a></section>`;if(!r)return `<section class="content inner-page"><div class="page-heading"><span class="overline">THE SAME NUMBERS, EVERYWHERE</span><h1>Find your<br><em>listening place.</em></h1><p>Match the room number on your guide, sign or personal plan. Choose a room to see its sample programme and directions.</p></div>${roomDiagram()}<div class="room-information"><p>These directions describe a fictional venue model. Confirm the actual route, entrances and access arrangements before visiting any real event.</p><a class="button" href="#access">Read the visit information ↗</a></div></section>`;const list=sessions.filter(s=>s.room===id&&s.day===state.day);return `<section class="content inner-page room-page"><a class="back" href="#rooms">← All rooms</a><div class="room-heading"><div class="room-number"><span>ROOM</span><b>${id}</b></div><div><span class="overline">${r.direction}</span><h1>${r.name}</h1><p>${r.note}. Check individual session details for the specific setting.</p><a class="text-button" href="#access">Access questions to confirm ↗</a></div></div><div class="room-page-grid"><section><div class="section-top"><h2>In this room</h2></div><div class="day-tabs" aria-label="Room programme day">${D.days.map(d=>`<button data-day="${d}" aria-pressed="${d===state.day}">${d}</button>`).join('')}</div><div class="room-session-list">${list.map(row).join('')}</div></section><aside>${roomDiagram(id)}<a class="text-button" href="guide.html#page-7">Find this room in the pocket guide ↗</a></aside></div></section>`;}
function downloadPlan(){const lines=['INTERVAL — MY PERSONAL PLAN','Fictional festival / not a booking or admission pass',''];for(const day of D.days){const list=ordered(state.plan).filter(s=>s.day===day);if(list.length){lines.push(day.toUpperCase());for(const s of list)lines.push(`${clock(s)} | ${s.title}`,`Room ${s.room} — ${room(s).name}`,`${s.seated?'All seated':'Mixed seating'} | ${s.light} | ${s.type}`,'');}}lines.push(`Break preference: ${state.minBreak} minutes. Not a walking-time estimate.`,'All venue conditions are illustrative.');try{const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='INTERVAL-my-plan.txt';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Your plain-text plan is ready to save.');}catch(_){notify('The download could not start. You can make a sample pass and use Print instead.');}}
function review(){if(!state.plan.length)return `<section class="content empty"><h1>Start with a session.</h1><p>A sample pass needs at least one session in your plan.</p><a class="button primary" href="#programme">Find a session</a></section>`;return `<section class="content inner-page"><a class="back" href="#plan">← Back to my plan</a><div class="page-heading"><span class="overline">REVIEW / SAMPLE PASS</span><h1>Keep the details<br><em>close.</em></h1><p>Review your choices, then create a printable keepsake. It is not a ticket or reservation.</p></div><div class="plan-layout"><div class="review-list">${ordered(state.plan).map(s=>`<article><span>${s.day} / ${clock(s)}</span><h2>${s.title}</h2><p>Room ${s.room} · ${room(s).name}</p></article>`).join('')}<a class="text-button" href="#plan">Edit my choices ↗</a></div><form id="pass-form" class="pass-form" novalidate><h2>Make it yours.</h2><label for="pass-name">Name on your sample pass <span>(optional)</span></label><input id="pass-name" name="name" maxlength="50" placeholder="Your first name" autocomplete="off"><p class="small">Stored only in this browser. No email or payment details are requested.</p><label class="check-label" for="demo-consent"><input id="demo-consent" name="consent" type="checkbox" aria-describedby="consent-error">I understand this is a sample pass and does not grant admission.</label><p class="form-error" id="consent-error" hidden>Please confirm that this is a sample pass.</p><button class="button primary" type="submit">Create my sample pass ↗</button></form></div></section>`;}
function pass(){if(!state.pass)return `<section class="content empty"><h1>Your pass is waiting<br>for your choices.</h1><p>Changes to your plan require a fresh sample pass so its details stay accurate.</p><a class="button primary" href="#plan">Review my plan</a></section>`;return `<section class="content inner-page pass-page"><div class="page-heading no-print"><span class="overline">YOUR SAMPLE PASS IS READY</span><h1>A little less<br>to <em>remember.</em></h1><p>Keep it on screen or print it. No booking was made.</p></div><article class="sample-pass"><header><span class="brand">INTER<span>VAL</span></span><span>SAMPLE<br>NOT VALID FOR ENTRY</span></header><div class="pass-name"><span>MADE FOR</span><h2>${esc(state.pass.name||'A curious listener')}</h2></div>${ordered(state.pass.ids).map(s=>`<div class="pass-session"><div><b>${s.day} / ${clock(s)}</b><h3>${s.title}</h3></div><a href="#room/${s.room}" class="pass-room" aria-label="Open Room ${s.room} guide">ROOM<br><strong>${s.room}</strong></a></div>`).join('')}<footer><span>MAKE SPACE FOR LISTENING.</span><span>CONCEPT EDITION / LOCAL DEMO</span></footer></article><div class="pass-actions no-print"><button class="button primary" data-action="print">Print sample pass</button><a class="button" href="#plan">Edit my plan</a><button class="text-button" data-action="download-plan">Download plain-text plan ↓</button><button class="text-button" data-action="clear-pass">Delete sample pass</button></div><p class="small no-print">All sessions and rooms are fictional. Editing your plan invalidates this pass until you recreate it.</p></section>`;}
function access(){return `<section class="content inner-page"><div class="page-heading"><span class="overline">PLAN YOUR VISIT / CONCEPT VENUE</span><h1>More context.<br>Fewer <em>unknowns.</em></h1><p>Check what a session will feel like before you add it. This guide demonstrates the information a real event should confirm with its venue and audience.</p></div><div class="access-grid"><article class="access-intro"><span class="overline">THREE ROOMS / ONE PLACE</span><h2>Find your<br>own pace.</h2><p>The concept places three rooms around one welcome desk. This is an information model, not a surveyed floor plan.</p><a class="button primary" href="#rooms">Open the room directory ↗</a><div class="room-directory">${Object.entries(D.rooms).map(([n,r])=>`<div><b>${n}</b><span><strong>${r.name}</strong><small>${r.direction}</small></span></div>`).join('')}</div></article><div class="access-details"><details open><summary>Seating, light and sound</summary><p>Each session names its seating format, lighting and sound source. “All seated” describes availability in the sample programme; it is not a medical or sensory-safety guarantee. Volume levels would need a production review.</p></details><details><summary>Step-free access and facilities</summary><p>A real venue survey must confirm step-free entrances, room thresholds, accessible toilets, wheelchair spaces and companion arrangements. These are open requirements, not verified features of this fictional venue.</p></details><details><summary>Taking a break</summary><p>The concept calls for clear exit information, a place away from amplified sound and a published re-entry policy. Staff, space and operating procedures would be agreed before any launch.</p></details><details><summary>Information in other formats</summary><p>A plain-text programme, readable signage and printed directions should complement this digital experience. The identity collection includes a printable programme and directional signs.</p><a href="guide.html">Open the pocket listening guide ↗</a></details><div class="preferences"><h2>Reading preference</h2><button class="button" data-action="large-text" aria-pressed="${state.large}">${state.large?'Use standard text':'Use larger text'}</button><p class="small">Your browser’s reduced-motion preference is also respected. There is no autoplay audio.</p></div></div></div></section>`;}
function render(focus=false){const active=document.activeElement, activeId=active?.dataset?.id, activeAction=active?.dataset?.action;const [route,id]=(location.hash.slice(1)||'programme').split('/');const view=route==='programme-list'?'programme':route;main.innerHTML=view==='rooms'?rooms():view==='room'?rooms(id):view==='alternatives'?alternatives(id):view==='session'?detail(id):view==='plan'?plan():view==='review'?review():view==='pass'?pass():view==='access'?access():programme();document.body.classList.toggle('large-text',state.large);$('#plan-count').textContent=state.plan.length;document.querySelectorAll('[data-nav]').forEach(el=>{if(el.dataset.nav===(view==='session'?'programme':['review','pass','alternatives'].includes(view)?'plan':['rooms','room'].includes(view)?'access':view))el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});document.title=`${view==='room'?(D.rooms[id]?.name||'Room'):view==='rooms'?'Room directory':view==='alternatives'?'Compatible alternatives':view==='session'?(byId(id)?.title||'Session'):view==='plan'?'My plan':view==='review'?'Review':view==='pass'?'Sample pass':view==='access'?'Plan your visit':'Make space for listening'} — INTERVAL`;if(focus){main.focus();if(route==='programme-list')$('#programme-list')?.scrollIntoView?.({behavior:'instant'});else window.scrollTo({top:0,behavior:'instant'});}else if(active&&main.contains(active)===false&&active!==document.body){const replacement=activeId?main.querySelector(`[data-id="${activeId}"]`):activeAction?main.querySelector(`[data-action="${activeAction}"]`):null;(replacement||main).focus();}}
let pending=null,returnTarget=null;
function closeDialog(){const dialog=$('#decision');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');pending=null;if(returnTarget?.isConnected)returnTarget.focus();returnTarget=null;}
function add(id,trigger){const s=byId(id);if(!s||s.full||state.plan.includes(id))return;const conflicts=state.plan.filter(x=>overlap(s,byId(x)));if(conflicts.length){pending={id,conflicts};returnTarget=trigger;$('#decision-body').innerHTML=`<span class="overline">A MOMENT TO CHOOSE</span><h2 id="decision-title">These sessions overlap.</h2><p>You already have ${conflicts.length===1?'a session':'sessions'} at this time. Keep your plan, or replace the overlapping choice${conflicts.length===1?'':'s'}.</p><div class="conflict-current"><span>CURRENTLY IN YOUR PLAN</span>${conflicts.map(x=>`<p><b>${byId(x).title}</b><br>${byId(x).day} / ${clock(byId(x))}</p>`).join('')}</div><div class="conflict-new"><span>YOUR NEW CHOICE</span><p><b>${s.title}</b><br>${s.day} / ${clock(s)}</p></div><div class="dialog-actions"><button class="button" data-action="cancel-conflict" autofocus>Keep my plan</button><button class="button primary" data-action="replace">Replace ${conflicts.length} ${conflicts.length===1?'session':'sessions'}</button></div>`;const dialog=$('#decision');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');$('#decision [autofocus]').focus();return;}remember();state.plan.push(id);commit(`${s.title} added to your plan.`);}
document.addEventListener('click',e=>{const day=e.target.closest('[data-day]');if(day){state.day=day.dataset.day;render(false);$(`[data-day="${state.day}"]`).focus();announce(`${main.querySelectorAll('.session-row').length} ${main.querySelectorAll('.session-row').length===1?'session':'sessions'} on ${state.day}.`);return;}const button=e.target.closest('[data-action]');if(!button)return;const a=button.dataset.action,id=button.dataset.id;
if(a==='add')add(id,button);
if(a==='remove'&&valid(id)){remember();state.plan=state.plan.filter(x=>x!==id);commit(`${byId(id).title} removed.`);}
if(a==='replace'&&pending){const p=pending;remember();state.plan=state.plan.filter(x=>!p.conflicts.includes(x));state.plan.push(p.id);closeDialog();commit('Your overlapping selection was replaced.');main.focus();}
if(a==='cancel-conflict')closeDialog();
if(a==='undo'&&state.undo){state.plan=[...state.undo.plan];state.pass=state.undo.pass;state.undo=null;persist();render(false);main.focus();notify('Your previous plan was restored.');}
if(a==='dismiss')$('#notice').hidden=true;
if(a==='clear-filters'){state.query='';state.type='All';state.seated=false;state.window=null;render(false);$('#session-search').focus();announce(`${results().length} sessions shown.`);}
if(a==='interest'&&valid(id)){state.interest=state.interest.includes(id)?state.interest.filter(x=>x!==id):[...state.interest,id];persist();render(false);notify(state.interest.includes(id)?'Interest saved locally. No waitlist request was sent.':'Saved interest removed.');}
if(a==='large-text'){state.large=!state.large;persist();render(false);$('[data-action="large-text"]').focus();}
if(a==='download-plan')downloadPlan();
if(a==='use-alternative'&&valid(id)){const from=button.dataset.from;const other=state.plan.filter(x=>x!==from);if(state.plan.includes(from)&&!byId(id).full&&!state.plan.includes(id)&&fits(byId(id),other.map(byId))){remember();state.plan=other.concat(id);commit(`${byId(from).title} replaced with ${byId(id).title}.`);go('plan');}}
if(['clear-query','clear-type','clear-seated','clear-window'].includes(a)){if(a==='clear-query')state.query='';if(a==='clear-type')state.type='All';if(a==='clear-seated')state.seated=false;if(a==='clear-window')state.window=null;render(false);$('#session-search')?.focus();announce(`${results().length} matching sessions.`);}
if(a==='print')window.print();
if(a==='clear-pass'){state.pass=null;persist();go('plan');notify('Your sample pass was deleted. Your plan is kept.');}
});
$('#decision').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
document.addEventListener('input',e=>{if(e.target.id==='session-search'){state.query=e.target.value;$('#session-results').innerHTML=resultMarkup();announce(`${results().length} matching sessions.`);}});
document.addEventListener('change',e=>{if(e.target.id==='break-preference'){state.minBreak=Number(e.target.value);persist();render(false);$('#break-preference')?.focus();announce('Break preference updated. Your sessions have been kept.');return;}if(e.target.id==='experience-filter'||e.target.id==='seated-filter'){if(e.target.id==='experience-filter')state.type=e.target.value;else state.seated=e.target.checked;$('#session-results').innerHTML=resultMarkup();announce(`${results().length} matching sessions.`);}if(e.target.id==='demo-consent'&&e.target.checked){$('#consent-error').hidden=true;e.target.removeAttribute('aria-invalid');}});
document.addEventListener('submit',e=>{if(e.target.id==='window-form'){e.preventDefault();const start=$('#arrival-time').value,end=$('#leaving-time').value,ok=/^([01]\d|2[0-3]):[0-5]\d$/.test(start)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(end)&&start<end;if(!ok){$('#window-error').textContent='Enter both times, with leaving later than arrival.';$('#window-error').hidden=false;$('#leaving-time').setAttribute('aria-invalid','true');$('#leaving-time').focus();return;}state.window={start,end};render(false);$('#arrival-time').focus();announce(`${results().length} sessions fit your visit.`);return;}if(e.target.id==='search-form'){e.preventDefault();return;}if(e.target.id!=='pass-form')return;e.preventDefault();const box=$('#demo-consent');if(!box.checked){$('#consent-error').hidden=false;box.setAttribute('aria-invalid','true');box.focus();announce('Please confirm that this is a sample pass.');return;}if(!state.plan.length){go('plan');return;}state.pass={name:$('#pass-name').value.trim().slice(0,50),ids:[...state.plan]};persist();go('pass');announce('Your sample pass is ready. No booking was made.');});
window.addEventListener('hashchange',()=>render(true));if(study==='empty')state.query='unmatched sample search';if(study){const bar=document.querySelector('.concept-bar>span');if(bar)bar.textContent='INTERACTION STUDY / ISOLATED SAMPLE CHOICES';}render(false);if(study==='conflict')add('objects-in-motion',main);
})();
